language: node_js
node_js: "10"


before_install:
  - export TZ='Asia/Shanghai'
  - cd themes/next-7.7.1
  - git clone https://github.com/theme-next/theme-next-pace source/lib/pace
  - git clone https://github.com/theme-next/theme-next-three source/lib/three
  - git clone https://github.com/theme-next/theme-next-canvas-nest source/lib/canvas-nest
  - git clone https://github.com/theme-next/theme-next-canvas-ribbon source/lib/canvas-ribbon
  - git clone https://github.com/theme-next/theme-next-pdf source/lib/pdf
  - cd .. && cd ..
install:
  - npm install -g hexo-cli
  - npm install
  - npm audit fix

script:
  - hexo clean
  - hexo g

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config  --global user.name "Qi Zhao"
  - git config  --global user.email "956361916@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push  --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - Backup
env:
 global:
   - GH_REF: github.com/ZhaoQi99/ZhaoQi99.github.io.git