dist: focal
language: node_js
node_js: "12"

before_install:
  - git config  --global user.name "Qi Zhao"
  - git config  --global user.email "zhaoqi99@outlook.com"

install:
  - export TZ='Asia/Shanghai'
  - cd themes/next-7.7.1
  - git clone https://github.com/theme-next/theme-next-pace source/lib/pace
  - git clone https://github.com/theme-next/theme-next-three source/lib/three
  - git clone https://github.com/theme-next/theme-next-canvas-nest source/lib/canvas-nest
  - git clone https://github.com/theme-next/theme-next-canvas-ribbon source/lib/canvas-ribbon
  - git clone https://github.com/theme-next/theme-next-pdf source/lib/pdf
  - cd .. && cd ..
  - npm install -g hexo-cli
  - npm install
  - npm audit fix


env:
  global:
    - GH_REF: github.com/ZhaoQi99/ZhaoQi99.github.io.git

jobs:
  allow_failures:
    - env: Allow_Failed=true
  
  include:
    - stage: submodule
      name: "Update submodule to latest"
      install: skip
      script:
        - git clone --depth=1 --branch=Backup https://${GH_REF} backup
        - cd backup
        - git submodule update --init
        - git submodule update --remote
        - git add .
        - git commit -m "Travis CI Auto Update CTF submodule at `date +"%Y-%m-%d %H:%M"`"
        - git push  "https://${GH_TOKEN}@${GH_REF}" Backup:Backup
      env:
        - Allow_Failed=true

    - stage: Build
      name: "Generate Hexo files"
      script:
        - bash ctf_post.sh replace
        - touch db.json && hexo clean
        - touch db.json && hexo g

    - stage: deploy
      name: "Deploy to Github pages"
      script:
        - git submodule update --remote # 保证最新
        - bash ctf_post.sh replace
        - touch db.json &&  hexo clean
        - touch db.json &&  hexo g
      after_success:
        - git clone https://${GH_REF} .deploy_git
        - cd .deploy_git
        - git checkout master
        - cd ../
        - mv .deploy_git/.git/ ./public/
        - cd ./public
        - git add .
        - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
        - git push  --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

stages:
  - name: submodule
    if: branch = Backup AND commit_message !~ ^Travis$
  - name: build
    if: branch NOT IN (master, Backup)
  - name: deploy
    if: branch = Backup AND commit_message !~ ^Travis$
