language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai'

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - ls
  - git checkout master
  - cd ../
  - ls
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "Qi Zhao"
  - git config user.email "zhaoqi99@outlook.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  #- git push  --quiet "https://${GT_Token}@${GH_REF}" master:master

branches:
  only:
    - Backup
env:
 global:
   - GH_REF: github.com/Zhaoqi99/Zhaoqi99.github.io.git