# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 温柔小猪
subtitle:
description:
author: Zhao Qi
language: zh-CN
timezone:
keywords: 赵旗,Qi Zhao,SNNU,ZhaopQi99,Python,陕西师范大学

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zhaoqi.vip
root: /
permalink: posts/:abbrlink/
# :day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "404.html"
  - "./CTF/**/*.md"



# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)

# https://github.com/im0o/hexo-generator-index-custom
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
plugin:

## Themes: https://hexo.io/themes/
theme: next-7.7.1

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:ZhaoQi99/ZhaoQi99.github.io.git
    #coding: git@git.coding.net:zhaoqi99/zhaoqi99.coding.me.git
  branch: master

#Avatar
avatar: /images/avatar.png

#Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
# hexo-seo will generate sitemap.xml
sitemap:
  path: sitemap.xml
  tags: true
  categories: true

baidusitemap:
  path: baidusitemap.xml

# https://github.com/hexojs/hexo-generator-feed
feed:
  enable: true
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss.xml
  limit: 20
  hub:
  content: false
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  autodiscovery: true

# https://github.com/alexbruno/hexo-generator-json-feed
jsonFeed:
	spec: feed

# https://github.com/rozbo/hexo-abbrlink
abbrlink:
  alg: crc32
  rep: dec

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false


# Security
encrypt:
  enable: true

# https://github.com/theme-next/hexo-filter-optimize
filter_optimize:
  enable: false
  remove_query_string: true
  remove_comments: false
  css:
    enable: true
    bundle: true
    delivery: true
    inlines:
    excludes:
  js:
    # bundle loaded js file into the one
    bundle: false
    excludes:
  priority: 12


# https://github.com/tea3/hexo-include-markdown
include_markdown:
  dir: source   # Base directory of template markdown
  verbose : true # If you want to check the path of markdown that use <!-- md --> tag , please set the true.


# https://github.com/hexojs/hexo-generator-archive
archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: false
  daily: false
  order_by: -date

marked:
  smartypants: false # https://github.com/theme-next/hexo-theme-next/issues/462
  prependRoot: true
  postAsset: true