# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 温柔小猪
subtitle:
description:
author: Zhao Qi
language: zh-CN
timezone:
keywords: 赵旗,Qi Zhao,SNNU,ZhaopQi99,Python,陕西师范大学

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zhaoqi.vip
root: /
permalink: posts/:abbrlink/
# :day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: "CTF/*/*/*.md"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#RSS订阅
plugin:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap

## Themes: https://hexo.io/themes/
theme: next-7.7.1

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:ZhaoQi99/ZhaoQi99.github.io.git
    #coding: git@git.coding.net:zhaoqi99/zhaoqi99.coding.me.git
  branch: master

#Avatar
avatar: /images/avatar.png

#Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
#Pet
live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-haruto
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
# 自动生成sitemap
sitemap:
  path: sitemap.xml
  tags: true
  categories: true
baidusitemap:
  path: baidusitemap.xml
#Rss
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  
# abbrlink config
abbrlink:
  alg: crc32
  rep: dec

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false


# Security
encrypt:
    enable: true

filter_optimize:
  enable: false
  remove_query_string: true
  remove_comments: false
  css:
    enable: true
    bundle: true
    delivery: true
    inlines:
    excludes:
  js:
    # bundle loaded js file into the one
    bundle: false
    excludes:
  priority: 12
admin:
    deployCommand: 'hexo-deploy.bat'
    
include_markdown:
  dir: source   # Base directory of template markdown
  verbose : true # If you want to check the path of markdown that use <!-- md --> tag , please set the true.

excerpt_length: 300